### ISSUE TITLE
[discussion] libuv as a separate package

### ISSUE THREAD

**Issue by dselivanov** [r-lib/fs#243]
At the moment there are at least two packages which use `libuv` - `fs` and `httpuv`. I'm developing another one (at the moment using more or less same approach as here as in the `httpuv` - copying it to `/src` and providing proper Makevars). 
@jimhester @wch  don't you guys think it might make sense to create separatate `libuv` package that will just provide static lib `libuv.a` and headers? so other packages can link to it.

**Comment by wch** [comment]
We've briefly talked about making libuv available in a separate package, but we haven't done it mostly because we've had other priorities. There are some advantages to having a separate package, but there are drawbacks in terms of maintenance. I think that other package developers would also start to ask for frequent CRAN releases to keep up with the libuv release cycle, which is a nontrivial responsibility.

If we make libuv.a available for static linking, that also increases the probability of hard-to-reproduce problems where someone (for example) builds pkgA 1.0 with libuv 1.1, and someone build pkgA 1.0 with libuv 1.2. These installations of pkgA could behave differently even though they have the same version.

Breaking changes: what happens when libuv changes its API, as it did from the 0.x series to 1.x?  When this transition happened, all we had to do was fix httpuv to work with the new API. But if there was a libuv package, we'd probably have to make a new package (for example, libuv2), but then we'd be responsible for maintaining both packages indefinitely.

I'm not saying that these things are necessarily show stoppers. We just haven't gotten to the point where we want to make the commitment to maintaining a separate libuv package -- or at least, I haven't.

**Comment by dselivanov** [comment]
@wch all points are very valid.

> I think that other package developers would also start to ask for frequent CRAN releases to keep up with the libuv release cycle, which is a nontrivial responsibility.

I believe this can be solved by managing expectations and just having scheduled pkg updates, say 1-2 times a year.

> If we make libuv.a available for static linking, that also increases the probability of hard-to-reproduce problems where someone (for example) builds pkgA 1.0 with libuv 1.1, and someone build pkgA 1.0 with libuv 1.2. These installations of pkgA could behave differently even though they have the same version.

True, not easy problem

> Breaking changes: what happens when libuv changes its API, as it did from the 0.x series to 1.x? When this transition happened, all we had to do was fix httpuv to work with the new API. But if there was a libuv package, we'd probably have to make a new package (for example, libuv2), but then we'd be responsible for maintaining both packages indefinitely.

Here we assume that libuv follows semantic versioning. So breaking changes  are expected during 0.* -> 1.* upgrade. Also same thing can happen shared libraries which are installed with package managers. So in theory same could happen if say `libcurl`  will have major version with breaking change... 

> I'm not saying that these things are necessarily show stoppers. We just haven't gotten to the point where we want to make the commitment to maintaining a separate libuv package -- or at least, I haven't.

Totally understandable.
