### ISSUE TITLE
Output of empty fs vectors

### ISSUE THREAD

**Issue by lionel-** [r-lib/fs#255]
I was confused for a while because I thought that `vec_ptype(fs)` stripped the class. Actually the class was still there, but empty fs vectors print like empty character vectors:

```r
empty <- fs_path(c("foo", "bar"))[0]

empty
#> character(0)

class(empty)
#> [1] "fs_path"   "character"
```

Perhaps one of these output would make sense:

```r
empty
#> fs_path(character(0))

empty
#> <fs_path>
#> character(0)
```

**Comment by lionel-** [comment]
Related but minor, names are not shown:

```r
set_names(fs_path(c("foo", "bar")), c("a", "b"))
#> foo bar
```

**Comment by jimhester** [comment]
These behaviors are actually intentional, though I can see how they might be confusing. I generally don't like having ornamentation on the print output if I can avoid it, and the vectors are named mainly to make using `purrr::map_dfr()` with them more natural, as shown in the last example in the readme (just above https://github.com/r-lib/fs#feedback-wanted).

printing the names looks weird and is confusing, so that is why they aren't printed. (I prototyped it when I was writing the print method)

**Comment by lionel-** [comment]
Sorry to reiterate this feature request but I just got very confused again while debugging a vctrs issue. This is very misleading IMO:

```r
vctrs::vec_ptype(fs::fs_perms(1))
#> character(0)
```
