### ISSUE TITLE
Failed fs_1.4.1 installation on AIX7.2 due to Makevars 

### ISSUE THREAD

**Issue by bergen288** [r-lib/fs#277]
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server with no internet access. Below is my R CMD INSTALL statement and its error:
R CMD INSTALL -l /software/R/site-library fs_1.4.1.tar.gz
"Makevars", line 8: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 11: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 12: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 14: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 15: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 17: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 18: make: 1254-055 Dependency line needs colon or double colon operator.
"Makevars", line 20: make: 1254-055 Dependency line needs colon or double colon operator.
make: 1254-058 Fatal errors encountered -- cannot continue.
ERROR: compilation failed for package 'fs'
[fs.log](https://github.com/r-lib/fs/files/4663917/fs.log)

I tried the dev fs version (fs-master.zip) with the same error.  Can you please tell me how to fix it?

**Comment by jimhester** [comment]
You need to use GNU make, as noted in the [system requirements](https://github.com/r-lib/fs/blob/bdc82beacbea374d85fdf642f42c63baa534bd6a/DESCRIPTION#L21) for the package.

FWIW if you continue to have installation issues with various packages rather than opening them at the individual package repositories please instead post the question at <https://community.rstudio.com>, the community will likely be able to help you.
