### ISSUE TITLE
Some operations are much slower than base

### ISSUE THREAD

**Issue by wch** [r-lib/fs#295]
For example:

```R
library(fs)
system.time({
  for (i in 1:1000) file_exists('DESCRIPTION')
})
#>    user  system elapsed 
#>   0.523   0.016   0.539

system.time({
  for (i in 1:1000) file.exists('DESCRIPTION')
})
#>    user  system elapsed 
#>   0.002   0.001   0.003
```

Similarly, replacing an instance of `dir_copy` with equivalent base code results in a significant speedup. For this test, the time spent in the copying code went from 370ms to 10ms. This is a real-world case where the speed impact is noticeable. https://github.com/rstudio/sass/pull/53

It is harder to get the code right with base functions, so it would be nice to use fs.

Sorry this isn't more specific about exactly which operations are slow. However, when I profiled it, it looked like a lot of time for `file_exists` was spent dealing with tibbles. (Note that it had to be profiled on R 3.6, since the profiler in R 4.0 has a bug and doesn't generate useful data.)

**Comment by jimhester** [comment]
Performance was not a specific goal of fs.

In general `.Call()` has non-negligible overhead compared to `.Primitive()` or `.Internal()`, so in many cases it may be impossible to fully reach the same performance.

In this particular case the performance difference is exacerbated because the implementation of `fs::file_exists()` internally uses `fs::file_info()` which queries much more information than just the file's existence, whereas `file.exists()` just checks for file existence.

tibble construction does seem to cause non-negligible slowdown, perhaps it would be worth adding an option so it could be disabled for performance critical code.

**Comment by jimhester** [comment]
In the `file_exists()` case it was pretty straightforward to have a comparable implementation to `file.exists()`, so I have done that now.

``` r
library(fs)
system.time({
  for (i in 1:1000) file_exists('DESCRIPTION')
})
#>    user  system elapsed 
#>   0.018   0.002   0.020
system.time({
  for (i in 1:1000) file.exists('DESCRIPTION')
})
#>    user  system elapsed 
#>   0.002   0.001   0.003
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think it is really possible to get much faster, as I said we start running into `.Call()` overhead.

**Comment by jimhester** [comment]
`dir_copy()` is more complicated and there is no direct equivalent to base functions. However in the benchmark you mention you run it for 30 times and it takes 800ms total, so each run is still only ~25ms total. Basically doing any non-trivial operation with the R interpreter usually takes on the order of 1ms, so we would have to implement all the dir_copy logic in C to get much speed benefit I think.
