### ISSUE TITLE
`link_create` cannot create soft file symbol link on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [r-lib/fs#79]
Thank you guys for this amazing package.

I found that `fs::link_create` could not create ***soft*** file symbol link on Windows but only soft directory symbol link. However `base::file.symlink` could:

```r
library(fs)

dir <- dir_create("dir")
file <- file_create(path(dir, "file.txt"))

link_create(path_abs(dir), path_abs("dir_link"))
link_create(path_abs(file), path_abs("file_link"))
file.symlink(path_abs(file), path_abs("file_link_base_r"))
```

```powershell
## In powershell
> ls

## Mode                LastWriteTime         Length Name                                                                         
## ----                -------------         ------ ----                                                                         
## d-----         2018/3/3      0:32                dir                                                                          
## d----l         2018/3/3      0:32                dir_link                                                                     
## d----l         2018/3/3      0:32                file_link                                                                    
## -a---l         2018/3/3      0:32              0 file_link_base_r
```

Is there any way to create soft file symbol link using `fs` package?

**Comment by jimhester** [comment]
`fs::link_create()` currently uses junctions on windows, which only support linking directories. This is because the Windows API requires the process to be elevated as administrator to create symbolic links (for both files and directories) using the [`CreateSymbolicLink()`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363866(v=vs.85).aspx) API. Recent versions of Windows 10 insiders builds include an option `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` to create symlinks without privelage elevation which is supported in libuv as of https://github.com/libuv/libuv/commit/89d31932a595fdec18dd19b70142816312ea2338, however currently we are using an older version of libuv in this package.

**Comment by hongyuanjia** [comment]
I see. Thanks for your detailed clarification. So it is still impossible to implement file linking on windows version lower than Windows 10.

I think I may close this issue as this is a limitation of Windows API, not a bug of `fs` itself. But an update of `fs::link_create()` documentation is recommended to avoid any confusing for Windows users. :)
