### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by rsangole** [r-lib/fs#90]
I get an error

    > install.packages('fs')
    Installing package into ‘/home/hw831/R/x86_64-pc-linux-gnu-library/3.3’
    (as ‘lib’ is unspecified)
    Warning in install.packages :
    package ‘fs’ is not available (for R version 3.3.2)

although the [CRAN ](https://cran.r-project.org/web/packages/fs/index.html)page specifies that the R dependency is >3.1.

Please advise.

**Comment by jimhester** [comment]
Try explicitly setting the type of package to source. e.g. `install.packages("fs", type = "source")`

**Comment by rsangole** [comment]
Hmm, no luck. Same error.

**Comment by rsangole** [comment]
> install.packages('fs',repos='http://cran.us.r-project.org')
worked though!

**Comment by rsangole** [comment]
Spoke too soon. I'm trying to install this package on an azure system running R 3.3.2. The install fails in the following way. Any ideas?

**version information**
![image](https://user-images.githubusercontent.com/6344050/37657902-9e307c2c-2c22-11e8-9112-44ae71735727.png)

**install & error information**
```
(> install.packages('fs',repos='http://cran.us.r-project.org')
Installing package into ‘/home/hw831/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  2  777k    2 19685    0     0  42888      0  0:00:18 --:--:--  0:00:18 42886100  777k  100  777k    0     0   639k      0  0:00:01  0:00:01 --:--:--  639k
* installing *source* package ‘fs’ ...
** package ‘fs’ successfully unpacked and MD5 sums checked
** libs
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c id.cc -o id.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'id.o' )failed
make: [id.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c fs.cc -o fs.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'fs.o' failed
make: [fs.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c file.cc -o file.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'file.o' failed
make: [file.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c link.cc -o link.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'link.o' failed
make: [link.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c path.cc -o path.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'path.o' failed
make: [path.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c utils.cc -o utils.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'utils.o' failed
make: [utils.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c dir.cc -o dir.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'dir.o' failed
make: [dir.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c error.cc -o error.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'error.o' failed
make: [error.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c unix/getmode.cc -o unix/getmode.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'unix/getmode.o' failed
make: [unix/getmode.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'RcppExports.o' failed
make: [RcppExports.o] Error 127 (ignored)
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c bsd/setmode.c -o bsd/setmode.o
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c bsd/strmode.c -o bsd/strmode.o
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I./libuv/include -I. -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c bsd/reallocarray.c -o bsd/reallocarray.o
cp -p -f libuv/m4/lt_obsolete.m4 libuv/m4/lt~obsolete.m4
(cd libuv && CC="gcc -std=gnu99" CFLAGS="-DU_STATIC_IMPLEMENTATION -O2 -g  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="" ./configure --quiet)
make --directory=libuv \
	HAVE_DTRACE=0
make[1]: Entering directory '/tmp/RtmpgupyEb/R.INSTALL57b46aa0b777/fs/src/libuv'
  CC       src/libuv_la-fs-poll.lo
  CC       src/libuv_la-inet.lo
  CC       src/libuv_la-threadpool.lo
  CC       src/libuv_la-uv-common.lo
  CC       src/libuv_la-version.lo
  CC       src/unix/libuv_la-async.lo
  CC       src/unix/libuv_la-core.lo
  CC       src/unix/libuv_la-dl.lo
  CC       src/unix/libuv_la-fs.lo
  CC       src/unix/libuv_la-getaddrinfo.lo
  CC       src/unix/libuv_la-getnameinfo.lo
  CC       src/unix/libuv_la-loop-watcher.lo
  CC       src/unix/libuv_la-loop.lo
  CC       src/unix/libuv_la-pipe.lo
  CC       src/unix/libuv_la-poll.lo
  CC       src/unix/libuv_la-process.lo
  CC       src/unix/libuv_la-signal.lo
  CC       src/unix/libuv_la-stream.lo
  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-timer.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-linux-core.lo
  CC       src/unix/libuv_la-linux-inotify.lo
  CC       src/unix/libuv_la-linux-syscalls.lo
  CC       src/unix/libuv_la-procfs-exepath.lo
  CC       src/unix/libuv_la-proctitle.lo
  CC       src/unix/libuv_la-sysinfo-loadavg.lo
  CC       src/unix/libuv_la-sysinfo-memory.lo
  CCLD     libuv.la

ar: `u' modifier ignored since `D' is the default (see `U')

make[1]: Leaving directory '/tmp/RtmpgupyEb/R.INSTALL57b46aa0b777/fs/src/libuv'
-shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o fs.so id.o fs.o file.o link.o path.o utils.o dir.o error.o unix/getmode.o RcppExports.o bsd/setmode.o bsd/strmode.o bsd/reallocarray.o ./libuv/.libs/libuv.a -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR

sh: line 2: -shared: command not found
/usr/lib64/microsoft-r/3.3/lib64/R/share/make/shlib.mk:6: recipe for target 'fs.so' failed
make: *** [fs.so] Error 127

ERROR: compilation failed for package ‘fs’

* removing ‘/home/hw831/R/x86_64-pc-linux-gnu-library/3.3/fs’

Warning in install.packages :
  installation of package ‘fs’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp1040QJ/downloaded_packages’
```

**Comment by jimhester** [comment]
Your system seems to be lacking a C++11 compiler, what is the output of `R CMD config --all`?

**Comment by gaborcsardi** [comment]
Can you try to compile other packages with C/C++ code from source? E.g. try the testthat package.

**Comment by rsangole** [comment]
@jimhester where do I run that command? in a shell?

@gaborcsardi Just tried `testthat` and it installed perfectly fine.

**Comment by rsangole** [comment]
![image](https://user-images.githubusercontent.com/6344050/37659469-768a063a-2c26-11e8-83d3-5a5ffbcbe51d.png)

**Comment by jimhester** [comment]
You will need to set these variables manually in either a [user or site Makevars](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Customizing-package-compilation)

Likely you need something like

```
CXX1X=g++
CXX1XSTD=-std=c++0x
```

**Comment by jimhester** [comment]
I have made changes to allow fs to be compiled on systems with C++11 support, so this should now compile without any changes needed on your system.

**Comment by rsangole** [comment]
Thanks @jimhester . Intemediate success for sure, but not full success.

I've added:
```
CXX1X=g++
CXX1XSTD=-std=c++0x
```
to `/home/hw831/.R/ Makevars-x86_64-pc-linux-gnu`.

As a result, the myriad of errors after `**libs*` have disappeared. Refer line 9-line 24: [link](https://gist.github.com/rsangole/f2858db2b663ac6a9efbee7620eca931#file-fs_error_after_custompackagecompilation-log-L9-L24).

But, I still get a failure, refer line 63 onwards: [link](https://gist.github.com/rsangole/f2858db2b663ac6a9efbee7620eca931#file-fs_error_after_custompackagecompilation-log-L63-L67)

**Comment by rsangole** [comment]
@jimhester My previous post was made in before you wrote

> I have made changes to allow fs to be compiled on systems with C++11 support, so this should now compile without any changes needed on your system.

Will try things out again.

**Comment by red-plant** [comment]
Hi, Same issue, tried downloading from github and "R CMD build fs" but still not working (no devtools since I need fs for that). My default  R g CXX1XSTD is -std=gnu++11, but also tried "c++0x" with no luck. Did you guys managed to solve it?

* checking for file ‘fs/DESCRIPTION’ ... OK
* preparing ‘fs’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘fs’ ...
** libs
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -pthread -I"/home/jaime-alaniz/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3U0YWo/r-base-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c id.cc -o id.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -pthread -I"/home/jaime-alaniz/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3U0YWo/r-base-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c file.cc -o file.o
In file included from ./libuv/include/uv.h:62:0,
                 from file.cc:6:
./libuv/include/uv-unix.h:104:28: error: ‘sem_t’ does not name a type; did you mean ‘sig_t’?
 # define UV_PLATFORM_SEM_T sem_t
                            ^
./libuv/include/uv-unix.h:136:9: note: in expansion of macro ‘UV_PLATFORM_SEM_T’
 typedef UV_PLATFORM_SEM_T uv_sem_t;
         ^~~~~~~~~~~~~~~~~
In file included from file.cc:6:0:
./libuv/include/uv.h:1461:27: error: ‘uv_sem_t’ was not declared in this scope
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                           ^~~~~~~~
./libuv/include/uv.h:1461:27: note: suggested alternative: ‘uv_req_t’
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                           ^~~~~~~~
                           uv_req_t
./libuv/include/uv.h:1461:37: error: ‘sem’ was not declared in this scope
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                     ^~~
./libuv/include/uv.h:1461:37: note: suggested alternative: ‘send’
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                     ^~~
                                     send
./libuv/include/uv.h:1461:42: error: expected primary-expression before ‘unsigned’
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                          ^~~~~~~~
./libuv/include/uv.h:1461:60: error: expression list treated as compound expression in initializer [-fpermissive]
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                                            ^
./libuv/include/uv.h:1462:31: error: variable or field ‘uv_sem_destroy’ declared void
 UV_EXTERN void uv_sem_destroy(uv_sem_t* sem);
                               ^~~~~~~~
./libuv/include/uv.h:1462:31: error: ‘uv_sem_t’ was not declared in this scope
./libuv/include/uv.h:1462:31: note: suggested alternative: ‘uv_req_t’
 UV_EXTERN void uv_sem_destroy(uv_sem_t* sem);
                               ^~~~~~~~
                               uv_req_t
./libuv/include/uv.h:1462:41: error: ‘sem’ was not declared in this scope
 UV_EXTERN void uv_sem_destroy(uv_sem_t* sem);
                                         ^~~
./libuv/include/uv.h:1462:41: note: suggested alternative: ‘send’
 UV_EXTERN void uv_sem_destroy(uv_sem_t* sem);
                                         ^~~
                                         send
./libuv/include/uv.h:1463:28: error: variable or field ‘uv_sem_post’ declared void
 UV_EXTERN void uv_sem_post(uv_sem_t* sem);
                            ^~~~~~~~
./libuv/include/uv.h:1463:28: error: ‘uv_sem_t’ was not declared in this scope
./libuv/include/uv.h:1463:28: note: suggested alternative: ‘uv_req_t’
 UV_EXTERN void uv_sem_post(uv_sem_t* sem);
                            ^~~~~~~~
                            uv_req_t
./libuv/include/uv.h:1463:38: error: ‘sem’ was not declared in this scope
 UV_EXTERN void uv_sem_post(uv_sem_t* sem);
                                      ^~~
./libuv/include/uv.h:1463:38: note: suggested alternative: ‘send’
 UV_EXTERN void uv_sem_post(uv_sem_t* sem);
                                      ^~~
                                      send
./libuv/include/uv.h:1464:28: error: variable or field ‘uv_sem_wait’ declared void
 UV_EXTERN void uv_sem_wait(uv_sem_t* sem);
                            ^~~~~~~~
./libuv/include/uv.h:1464:28: error: ‘uv_sem_t’ was not declared in this scope
./libuv/include/uv.h:1464:28: note: suggested alternative: ‘uv_req_t’
 UV_EXTERN void uv_sem_wait(uv_sem_t* sem);
                            ^~~~~~~~
                            uv_req_t
./libuv/include/uv.h:1464:38: error: ‘sem’ was not declared in this scope
 UV_EXTERN void uv_sem_wait(uv_sem_t* sem);
                                      ^~~
./libuv/include/uv.h:1464:38: note: suggested alternative: ‘send’
 UV_EXTERN void uv_sem_wait(uv_sem_t* sem);
                                      ^~~
                                      send
./libuv/include/uv.h:1465:30: error: ‘uv_sem_t’ was not declared in this scope
 UV_EXTERN int uv_sem_trywait(uv_sem_t* sem);
                              ^~~~~~~~
./libuv/include/uv.h:1465:30: note: suggested alternative: ‘uv_req_t’
 UV_EXTERN int uv_sem_trywait(uv_sem_t* sem);
                              ^~~~~~~~
                              uv_req_t
./libuv/include/uv.h:1465:40: error: ‘sem’ was not declared in this scope
 UV_EXTERN int uv_sem_trywait(uv_sem_t* sem);
                                        ^~~
./libuv/include/uv.h:1465:40: note: suggested alternative: ‘send’
 UV_EXTERN int uv_sem_trywait(uv_sem_t* sem);
                                        ^~~
                                        send
/usr/lib/R/etc/Makeconf:170: recipe for target 'file.o' failed
make: *** [file.o] Error 1
ERROR: compilation failed for package ‘fs’
* removing ‘/tmp/RtmpzTY5zv/Rinst2c3126a37586/fs’
      -----------------------------------
ERROR: package installation failed

**Comment by trb5me** [comment]
For me the following fix it:
`install.packages("Rcpp")`

**Comment by wangshun1121** [comment]
The same problem as @red-plant in R 3.6.0, and this problem can't be solved by installing "Rcpp"

**Comment by Alalalalaki** [comment]
Similar problem that "ERROR: compilation failed for package ‘fs’".

**Comment by addfunr3** [comment]
I had the same issues and did with a couple of other packages. I managed to get fs installed, but had to install Rtools first. Once I had, there was a section that kept coming up with a warning, happened four times but still installed:

src/win/fs.c: In function 'fs__unlink':
src/win/fs.c:784:5: warning: missing braces around initializer [-Wmissing-braces]
     FILE_BASIC_INFORMATION basic = { 0 };
     ^
src/win/fs.c:784:5: warning: (near initialization for 'basic.CreationTime') [-Wmissing-braces]

----

src/win/pipe.c: In function 'uv_pipe_chmod':
src/win/pipe.c:2140:3: warning: missing braces around initializer [-Wmissing-braces]
   SID_IDENTIFIER_AUTHORITY sid_world = SECURITY_WORLD_SID_AUTHORITY;
   ^
src/win/pipe.c:2140:3: warning: (near initialization for 'sid_world.Value') [-Wmissing-braces]

----

src/win/fs.c: In function 'fs__unlink':
src/win/fs.c:784:5: warning: missing braces around initializer [-Wmissing-braces]
     FILE_BASIC_INFORMATION basic = { 0 };
     ^
src/win/fs.c:784:5: warning: (near initialization for 'basic.CreationTime') [-Wmissing-braces]

----

src/win/pipe.c: In function 'uv_pipe_chmod':
src/win/pipe.c:2140:3: warning: missing braces around initializer [-Wmissing-braces]
   SID_IDENTIFIER_AUTHORITY sid_world = SECURITY_WORLD_SID_AUTHORITY;
   ^
src/win/pipe.c:2140:3: warning: (near initialization for 'sid_world.Value') [-Wmissing-braces]

**Comment by purod** [comment]
I have the same problem

In file included from ./libuv/include/uv.h:62:
./libuv/include/uv-unix.h:136:9: error: unknown type name 'sem_t'
typedef UV_PLATFORM_SEM_T uv_sem_t;
        ^
./libuv/include/uv-unix.h:104:28: note: expanded from macro 'UV_PLATFORM_SEM_T'
# define UV_PLATFORM_SEM_T sem_t

**Comment by Bsguerraa** [comment]
Found something for those still having problems:

I had problem with compilation of fs packages and others due to and error in semaphore.h from /usr/local/include

You could move this file or delete it, do it with care tho. It worked for me!
